FROM ubuntu:16.04
MAINTAINER zerogvt
RUN apt-get -y update
RUN apt-get install -y python-yaml python-jinja2 git
RUN git clone http://github.com/ansible/ansible.git --recursive /tmp/ansible
WORKDIR /tmp/ansible
ENV PATH /tmp/ansible/bin:/sbin:/usr/sbin:/usr/bin
ENV ANSIBLE_LIBRARY /tmp/ansible/library
ENV PYTHONPATH /tmp/ansible/lib:$PYTHON_PATH
RUN git clone http://github.com/zerogvt/muc_adn.git /tmp/muc_adn
ADD inventory /etc/ansible/hosts
WORKDIR /tmp/muc_adn
RUN ansible-galaxy install geerlingguy.jenkins -p ./roles/ && ansible-playbook configure-ci-server.yml -c local
EXPOSE 22 3000
ENTRYPOINT [“/usr/bin/foo”]