FROM ubuntu:16.04
MAINTAINER zerogvt
# next vars should be in our env
ARG jenkins_port
ARG jenkins_user
ARG jenkins_pass

RUN apt-get -y update

# install ansible from source
RUN apt-get install -y python-yaml python-jinja2 git
RUN git clone http://github.com/ansible/ansible.git --recursive /tmp/ansible
WORKDIR /tmp/ansible
ENV PATH $PATH:/tmp/ansible/bin
ENV ANSIBLE_LIBRARY /tmp/ansible/library
ENV PYTHONPATH /tmp/ansible/lib:$PYTHON_PATH

# get our build context off our gh repo
RUN git clone http://github.com/zerogvt/muc_adn.git /tmp/muc_adn
ADD inventory /etc/ansible/hosts
WORKDIR /tmp/muc_adn

# let ansible do the heavy lifting of installing/setting up jenkins 
RUN ansible-galaxy install geerlingguy.jenkins -p ./roles/ && \
    ansible-galaxy install flyapen.jenkins -p ./roles/ && \
    ansible-playbook jenkins_ansible.yml -i inventory -c local --extra-vars "jenkins_http_port=${jenkins_port}"

# expose 22 so we can ssh and inspect...
# and our jenkins port 
EXPOSE 22 ${jenkins_port}

# start up jenkins and let an open end command 
# to keep container alive (also handy status inspection)
CMD service jenkins start && tail -f /var/log/jenkins/jenkins.log
 
